# Generated by Django 5.0.6 on 2024-07-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='deadline',
        ),
    ]
