# Generated by Django 5.0.6 on 2024-07-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_date_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='days_left',
            field=models.IntegerField(default=0),
        ),
    ]
