# Generated by Django 5.0.6 on 2024-07-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
