# Generated by Django 5.0.6 on 2024-07-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_status',
            field=models.BooleanField(default=False),
        ),
    ]
